#!/bin/sh /etc/rc.common
. /sbin/wifi_daemon.sh

START=20
STOP=90

USE_PROCD=1

init_ngr_ipv6() {
	local wan6_conn_mode=$(uci get network.wan6.conn_mode 2> /dev/null)
	local wan_if_name=$(uci get network.wan.ifname 2> /dev/null)
	case "$wan6_conn_mode" in
		6to4)
		;;
		6rd)
		;;
		pass)
			brctl addif br-lan $wan_if_name
			ebtables -t broute -D BROUTING -j brouting_pass
			ebtables -t broute -F brouting_pass
			ebtables -t broute -X brouting_pass
			ebtables -t broute -N brouting_pass
			ebtables -t broute -I BROUTING 1 -j brouting_pass
			ebtables -t broute -A brouting_pass -i $wan_if_name -p IPv4 -j DROP
			ebtables -t broute -A brouting_pass -i $wan_if_name -p ARP -j DROP
			ebtables -D FORWARD -j forward_pass
			ebtables -F forward_pass
			ebtables -X forward_pass
			ebtables -N forward_pass
			ebtables -I FORWARD 1 -j forward_pass
			ebtables -A forward_pass -i $wan_if_name -p IPv4 -j DROP
			ebtables -A forward_pass -o $wan_if_name -p IPv4 -j DROP
			ebtables -A forward_pass -i $wan_if_name -p ARP -j DROP
			ebtables -A forward_pass -o $wan_if_name -p ARP -j DROP
			ebtables -D INPUT -j input_pass
			ebtables -F input_pass
			ebtables -X input_pass
			ebtables -N input_pass
			ebtables -I INPUT 1 -j input_pass
			ebtables -A input_pass -i $wan_if_name -j DROP
		;;
		static)
		;;
		dhcp)
			echo 0 > /proc/sys/net/ipv6/conf/$wan_if_name/autoconf
		;;
		auto)
			echo 1 > /proc/sys/net/ipv6/conf/$wan_if_name/autoconf
		;;
		pppoe)
		;;
		auto_detect)
			uci set network.wan6.proto=auto_detect
			autoDetect -P 0 $wan_if_name
		;;
	esac
	local spi_firewall_mode=$(uci get network.wan6.spi_firewall_mode 2> /dev/null)
	case "$spi_firewall_mode" in
		secured) 
			echo 0 > /proc/sys/net/ipv6/spi_firewall_mode
		;;
		open)
			echo 1 > /proc/sys/net/ipv6/spi_firewall_mode
		;;
	esac
}

do_swop() {
	swop -c check_vmode
	swop -c reset_vlan
	swop -c pppoe_mcast
}

init_switch() {
	setup_switch() { return 0; }

	include /lib/network
	setup_switch
	do_swop
}

start_service() {
	init_switch

	procd_open_instance
	procd_set_param command /sbin/netifd
	procd_set_param respawn
	procd_set_param watch network.interface
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}
	procd_close_instance
}

reload_service() {
	init_switch
	ubus call network reload
	/sbin/wifi brctlAddIf
	#monitor_wifi_switch &
	netmode=$(uci get system.@system[0].netmode 2> /dev/null)
	netmode=${netmode:-router}
	if [ "$netmode" = "router" ]; then
		/etc/init.d/miniupnpd restart
		/etc/init.d/trafficMeter restart
	fi
	/etc/init.d/igmpproxy restart
	/etc/init.d/xl2tpd restart
	/etc/init.d/openvpn restart
}

stop_service() {
	local factory_mode=$(envctl factory get factory_mode 2> /dev/null)
	if [ "$factory_mode" = "off" ]; then
		local netmode=""
		local wan_proto=""
		local miniupnpdpid=""
		local ripdpid=""
		local xl2tpdpid=""
		netmode=$(uci get system.@system[0].netmode 2> /dev/null)
		netmode=${netmode:-router}
		wan_proto=$(uci get network.vpn.proto 2> /dev/null)
		wan_proto=${wan_proto:-pptp}	
		if [ "$netmode" != "router" ]; then
			miniupnpdpid=$(ps | grep miniupnpd | grep -v "grep" | wc -l )
			ripdpid=$(ps | grep watchquagga | grep -v "grep" | wc -l)
			trafficmeterpid=$(ps | grep trafficMeter | grep -v "grep" | wc -l)
			blocksiteid=$(ps | grep blockSites | grep -v "grep" | wc -l)
			/etc/init.d/miniupnpd stop
			if [ -f /var/run/dnsmasq/*.pid ]; then
				/etc/init.d/dnsmasq stop
			fi
			if [ "$ripdpid" = "1" ]; then
				/etc/init.d/quagga stop
			fi
			if [ "$blocksiteid" = "1" ]; then
				/etc/init.d/blockSites stop
			fi
		fi
		xl2tpdpid=$(ps | grep xl2tpd | grep -v "grep" | wc -l)
		if [ "$wan_proto" != "l2tp" ] && [ "$xl2tpdpid" = "1" ]; then
			/etc/init.d/xl2tpd stop
		fi
	fi
	#monitor_wifi_switch_exit
	/sbin/wifi down
	ifdown -a
	if [ "$factory_mode" = "off" ]; then
		tw_vty -c "switchport 1 admin disable" 2> /dev/null
		tw_vty -c "switchport 2 admin disable" 2> /dev/null
		tw_vty -c "switchport 3 admin disable" 2> /dev/null
		tw_vty -c "switchport 4 admin disable" 2> /dev/null
		sleep 1
	fi
}

service_running() {
	ubus -t 120 wait_for network.interface
	local factory_mode=$(envctl factory get factory_mode 2> /dev/null)
	if [ "$factory_mode" = "off" ]; then
		tw_vty -c "switchport 1 admin enable" 2> /dev/null
		tw_vty -c "switchport 2 admin enable" 2> /dev/null
		tw_vty -c "switchport 3 admin enable" 2> /dev/null
		tw_vty -c "switchport 4 admin enable" 2> /dev/null
	fi
	mkdir -p /tmp/mtk/wifi/
	touch /tmp/mtk/wifi/normal_reload
	/sbin/wifi reload
	#monitor_wifi_switch &
	if [ "$factory_mode" = "off" ]; then
		local netmode=""
		local wan_proto=""
		local miniupnpdpid=""
		local ripdpid=""
		local xl2tpdpid=""
		/sbin/init_isolation.sh &
		ubus send dev_probe_refresh_fd
		netmode=$(uci get system.@system[0].netmode 2> /dev/null)
		netmode=${netmode:-router}
		wan_proto=$(uci get network.vpn.proto 2> /dev/null)
		wan_proto=${wan_proto:-pptp}
		if [ "$netmode" = "router" ]; then
			ripdpid=$(ps | grep watchquagga | grep -v "grep" | wc -l)
			blocksiteid=$(ps | grep blockSites | grep -v "grep" | wc -l)
			/etc/init.d/miniupnpd restart
			if [ ! -f /var/run/dnsmasq/*.pid ]; then
				/etc/init.d/dnsmasq restart
			fi
			if [ "$ripdpid" = "0" ]; then
				/etc/init.d/quagga restart
			fi
			if [ "$blocksiteid" = "0" ]; then
				/etc/init.d/blockSites restart
			fi
		fi
		xl2tpdpid=$(ps | grep xl2tpd | grep -v "grep" | wc -l)
		if [ "$wan_proto" = "l2tp" ] && [ "$xl2tpdpid" = "0" ]; then
				/etc/init.d/xl2tpd restart
		fi
	fi
	/etc/init.d/igmpproxy restart
	/etc/init.d/openvpn restart
	init_ngr_ipv6
}

validate_atm_bridge_section()
{
	uci_validate_section network "atm-bridge" "${1}" \
		'unit:uinteger:0' \
		'vci:range(32, 65535):35' \
		'vpi:range(0, 255):8' \
		'atmdev:uinteger:0' \
		'encaps:or("llc", "vc"):llc' \
		'payload:or("bridged", "routed"):bridged'
}

validate_route_section()
{
	uci_validate_section network route "${1}" \
		'interface:string' \
		'target:cidr4' \
		'netmask:netmask4' \
		'gateway:ip4addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_route6_section()
{
	uci_validate_section network route6 "${1}" \
		'interface:string' \
		'target:cidr6' \
		'gateway:ip6addr' \
		'metric:uinteger' \
		'mtu:uinteger' \
		'table:or(range(0,65535),string)'
}

validate_rule_section()
{
	uci_validate_section network rule "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr4' \
		'dest:cidr4' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_rule6_section()
{
	uci_validate_section network rule6 "${1}" \
		'in:string' \
		'out:string' \
		'src:cidr6' \
		'dest:cidr6' \
		'tos:range(0,31)' \
		'mark:string' \
		'invert:bool' \
		'lookup:or(range(0,65535),string)' \
		'goto:range(0,65535)' \
		'action:or("prohibit", "unreachable", "blackhole", "throw")'
}

validate_switch_section()
{
	uci_validate_section network switch "${1}" \
		'name:string' \
		'enable:bool' \
		'enable_vlan:bool' \
		'reset:bool'
}

validate_switch_vlan()
{
	uci_validate_section network switch_vlan "${1}" \
		'device:string' \
		'vlan:uinteger' \
		'ports:list(ports)'
}

service_triggers()
{
	procd_add_reload_trigger network wireless

	procd_open_validate
	validate_atm_bridge_section
	validate_route_section
	validate_route6_section
	validate_rule_section
	validate_rule6_section
	validate_switch_section
	validate_switch_vlan
	procd_close_validate
}

shutdown() {
    #monitor_wifi_switch_exit
	/sbin/wifi down
	ifdown -a
	sleep 1
}
