server {
    listen       80;
    listen       [::]:80;

    if (-e /etc/config/https/redirect_https) {
        rewrite ^(.*)$  /cgi-bin/do_ej.cgi?path=/http_msgwarning.htm last;
    }
    include /etc/nginx/service.conf;
}