#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=xl2tpd
RUN_D="/var/run/xl2tpd"
PID_F="/var/run/xl2tpd.pid"

start_service() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"

	wan_proto=$(uci -q get network.vpn.proto 2>/dev/null)
	[ "$wan_proto" != "l2tp" ] && return 1

	procd_open_instance
	procd_set_param command $BIN -D -l -p "$PID_F"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}
